#!/usr/bin/env python3
"""Embed Jupyter notebooks into a Kubernetes ConfigMap YAML.

Reads .ipynb files from zarf/notebooks/, strips output cells,
and generates zarf/manifests/sample-notebooks-configmap.yaml
with notebook JSON embedded as ConfigMap data entries.

Usage:
    python zarf/scripts/embed-notebooks.py

The ConfigMap YAML is auto-generated — do not edit it by hand.
Edit the source notebooks in zarf/notebooks/ instead.
"""
import json
import sys
import textwrap
from pathlib import Path

# Paths relative to project root
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
NOTEBOOKS_DIR = PROJECT_ROOT / "zarf" / "notebooks"
OUTPUT_FILE = PROJECT_ROOT / "zarf" / "manifests" / "sample-notebooks-configmap.yaml"

# Notebooks to include (order matters for README table)
INCLUDE_NOTEBOOKS = [
    "OTEL_Data_Generator.ipynb",
    "Dask_S3_Validation.ipynb",
]

# ConfigMap limit is 1 MiB; warn if we get close
MAX_CONFIGMAP_BYTES = 1_048_576
WARN_THRESHOLD = 0.8  # 80%


def strip_notebook(nb: dict) -> dict:
    """Strip outputs and execution counts from a notebook."""
    nb = json.loads(json.dumps(nb))  # deep copy
    for cell in nb.get("cells", []):
        if cell.get("cell_type") == "code":
            cell["outputs"] = []
            cell["execution_count"] = None
        # Remove cell IDs (non-essential, saves space)
        cell.pop("id", None)
    return nb


def yaml_block_scalar(text: str, indent: int = 4) -> str:
    """Format a string as a YAML block scalar (literal style |)."""
    prefix = " " * indent
    lines = text.split("\n")
    return "\n".join(prefix + line if line else "" for line in lines)


def main():
    if not NOTEBOOKS_DIR.is_dir():
        print(f"Error: notebooks directory not found: {NOTEBOOKS_DIR}", file=sys.stderr)
        sys.exit(1)

    # Process notebooks
    notebook_entries = {}
    for nb_name in INCLUDE_NOTEBOOKS:
        nb_path = NOTEBOOKS_DIR / nb_name
        if not nb_path.exists():
            print(f"Warning: {nb_name} not found, skipping", file=sys.stderr)
            continue
        with open(nb_path) as f:
            nb = json.load(f)
        stripped = strip_notebook(nb)
        # Compact JSON (no indent) to save space in ConfigMap
        nb_json = json.dumps(stripped, separators=(",", ":"), ensure_ascii=False)
        notebook_entries[nb_name] = nb_json
        print(f"  {nb_name}: {len(nb_json):,} bytes")

    # Build README content
    readme = textwrap.dedent("""\
        # Sample Notebooks

        These notebooks demonstrate out-of-core processing with Dask and S3.

        ## Available Notebooks

        | Notebook | Description | Data Size |
        |----------|-------------|-----------|
        | `OTEL_Data_Generator.ipynb` | Generate synthetic OTEL spans (same methodology as 1TB dataset) | Configurable |
        | `Dask_S3_Validation.ipynb` | Out-of-core Dask stress test with 30GB dataset | 30 GB |

        ## Getting Started

        These notebooks are **read-only** (mounted from ConfigMap). To edit and run:

        ```bash
        cp ~/sample-notebooks/OTEL_Data_Generator.ipynb ~/
        ```

        ## Environment Variables

        The following are pre-configured:
        - `DASK_SCHEDULER_ADDRESS`: Dask cluster endpoint
        - `S3_ENDPOINT`: S3 endpoint (if applicable)
        - `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`: S3 credentials

        ## Cluster Resources

        Default Dask cluster: 32 workers x 6 GiB = 192 GiB

        To scale workers:
        ```bash
        kubectl scale deployment cybersec-dask-default-worker -n dask --replicas=64
        ```
    """)

    # Build ConfigMap YAML
    yaml_parts = [
        "# Auto-generated by zarf/scripts/embed-notebooks.py",
        "# DO NOT EDIT — regenerate with: python zarf/scripts/embed-notebooks.py",
        "#",
        "# Notebooks embedded from zarf/notebooks/",
        "# Mounted read-only at /home/jovyan/sample-notebooks/ in JupyterHub",
        "---",
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        "  name: sample-notebooks",
        "  namespace: jupyterhub",
        "  labels:",
        "    app: jupyterhub",
        "    component: sample-notebooks",
        "data:",
        "  README.md: |",
    ]
    yaml_parts.append(yaml_block_scalar(readme))

    for nb_name, nb_json in notebook_entries.items():
        yaml_parts.append(f"  {nb_name}: |")
        yaml_parts.append(yaml_block_scalar(nb_json))

    yaml_content = "\n".join(yaml_parts) + "\n"

    # Size check
    size_bytes = len(yaml_content.encode("utf-8"))
    pct = size_bytes / MAX_CONFIGMAP_BYTES * 100
    print(f"\nConfigMap size: {size_bytes:,} bytes ({pct:.1f}% of 1 MiB limit)")
    if size_bytes > MAX_CONFIGMAP_BYTES:
        print("ERROR: ConfigMap exceeds 1 MiB limit!", file=sys.stderr)
        sys.exit(1)
    if pct > WARN_THRESHOLD * 100:
        print(f"WARNING: ConfigMap is {pct:.0f}% of limit", file=sys.stderr)

    # Write output
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(yaml_content)

    print(f"Wrote {OUTPUT_FILE}")
    print(f"  README.md + {len(notebook_entries)} notebooks embedded")


if __name__ == "__main__":
    main()
