---
# Group variables for all hosts

# Project identification (must match Tofu var.project)
project: "cybersec-dask"
aws_region: "us-east-1"

# RKE2 version
rke2_version: "v1.31.0+rke2r1"

# Dask configuration
dask_worker_replicas: 64
dask_worker_memory_limit: "8GB"
dask_worker_memory_request: "12Gi"
dask_image: "ghcr.io/dask/dask:latest"
