apiVersion: v1
kind: Namespace
metadata:
  name: dask
---
apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: cybersec-dask
  namespace: dask
spec:
  scheduler:
    service:
      type: NodePort
      ports:
        - name: tcp-comm
          port: 8786
          targetPort: 8786
          nodePort: 30086
        - name: tcp-dashboard
          port: 8787
          targetPort: 8787
          nodePort: 30087
    template:
      spec:
        restartPolicy: Always
        containers:
          - name: scheduler
            image: ghcr.io/dask/dask:2024.8.0
            imagePullPolicy: IfNotPresent
            args:
              - dask-scheduler
            ports:
              - containerPort: 8786
                name: tcp-comm
              - containerPort: 8787
                name: tcp-dashboard
            readinessProbe:
              tcpSocket:
                port: 8786
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              tcpSocket:
                port: 8786
              initialDelaySeconds: 15
              periodSeconds: 30
  worker:
    replicas: 2
    template:
      spec:
        restartPolicy: Always
        containers:
          - name: worker
            image: ghcr.io/dask/dask:2024.8.0
            imagePullPolicy: IfNotPresent
            args:
              - dask-worker
              - --nthreads
              - "2"
              - --memory-limit
              - 2Gi
            env:
              - name: DASK_DASHBOARD_ADDRESS
                value: ":8787"
            resources:
              requests:
                cpu: "250m"
                memory: 512Mi
              limits:
                cpu: "1"
                memory: 1Gi
